### PR TITLE
Chromedriver 75 compatibility

### PR DESCRIPTION
**Pull request by jbrichau**
Make the necessary changes to run Parasol with Chromedriver 75+ with w3c mode turned off, for now.

### CODE REVIEW

**Comment by jbrichau** [comment]
@Rinzwind We also will go metadataless when merging this PR because I used Iceberg. Seaside and Grease are also metadataless.

**Comment by noha** [comment]
Is there an ETA for this to be merged?

**Comment by jbrichau** [comment]
@noha I will just push the merge button tomorrow :)
Yes, there are some quirks in the code now to make it work with 'w3c compatibility off' but we will fix that asap to make Parasol w3c compatible for the future.

**Comment by noha** [comment]
ping

**Comment by jbrichau** [comment]
@Rinzwind :)

**Comment by noha** [comment]
Thanks ;)

**Pull request merged**
