### PR TITLE
Add the possibility to customize a component to test before the tests

### PR DESCRIPTION
**Pull request by jecisc**
This works in two ways:
- You can customize the component for all methods
- You can customize the component for some methods only

This add also a class comment to explain this.

### CODE REVIEW

**Comment by jecisc** [comment]
https://github.com/SeasideSt/Parasol/issues/3

**Comment by Rinzwind** [comment]
I took a look at the proposed changes and had the following thoughts:

* It might be nice to include tests that depend on `#initializeComponentUnderTest:` and `#initializationMap` so that this part of the framework also gets tested.
* One thing I don’t like about `#initializationMap` is that it puts the information about how the component is initialized for each test selector away from the test selectors. So, when looking at a test method, I don't immediately see whether it relies on a specific initialization block or not. It might be nicer to use a pragma inside the test method. Something like `<componentInitializer: #initializeMultiplePages>`, where `#initializeMultiplePages` is the selector of an auxiliary method that is then used to initialize the component.

**Comment by jecisc** [comment]
Ok
For the first point, yes indeed. I'll do. 

For the second point, perfect! This was also something bothering me but I did not thought of a way to includes the initialization in the test. Pragma should do the trick. I have some university project to finish now, when I'll finish I'll correct this PR. 

Thank you for this comment!

**Comment by jecisc** [comment]
@Rinzwind New commit to review.

**Comment by jecisc** [comment]
No news?

**Comment by Rinzwind** [comment]
Sorry, I haven't gotten around to looking at this yet. It's on the TODO list though.

**Comment by Rinzwind** [comment]
Sorry for taking a long time before taking another look at this. Note that `PragmaCollector` does not exist on Squeak and GemStone, but I already fixed that (in commit https://github.com/SeasideSt/Parasol/commit/87638ee73dbbe7246ceda2d9bc4f9b5e06c75289).

One comment I still have is that when the pragma is used, a component gets initialized twice. For example in the test `#testComponentWithSpecificCustomization`, the component gets initialized through both the method `BPWebElementTestCase>>#initializeComponentUnderTest:` and the method `BPWebElementTestCase>>#initializeComponentForSpecificTest:`. And of course, it also gets initialized through its own `#initialize` method, so maybe I should not say it gets initialized twice, but thrice. Maybe it would be better to speak of “configuring” the component, or something like that, rather than “initializing” it. I’m not sure yet what alternative to propose here though.

**Pull request closed without merging**
