### PR TITLE
Fix for #14

### PR DESCRIPTION
**Pull request by pdebruic**

### CODE REVIEW

**Comment by Rinzwind** [comment]
Sorry for taking so long to take a look at this! I see there's a comment that may still need some work? I'm referring to the comment in `BPRemoteWebDriver>>#initWithCapabilities:` that says `"I don't know how to […]"`:

https://github.com/SeasideSt/Parasol/pull/15/commits/b0bc459c4f4853aa642e36319cf417528cb83f7a#diff-f252e53767a232a2a9f0a3b7815172a6R15

I'm not sure how to reproduce the situation where the 302-response is given. I tried using selenium-server-standalone-3.13.0.jar and chromedriver 2.40.565386 but I didn't hit the bug. The code to handle responses with status code 303 and 302 was originally introduced in Parasol-Core-KrisGybels.25 and Parasol-Core-KrisGybels.26, but the comments unfortunately don't mention why this was added and under what conditions those responses are given. The bug with the missing return statement seems to have been introduced in the changes between Parasol-Core-chaerle.42 and Parasol-Core-JohanBrichau.39 (there are some versions missing there from the [SqueakSource3 repository](http://ss3.gemstone.com/ss/Parasol.html)).

**Comment by Rinzwind** [comment]
It would be better if we could fix that now and have a test for it. I don't know (or remember) how to reproduce the situation where one gets the 302 response. Do you have some info on how to reproduce that?

**Comment by pdebruic** [comment]
I disagree but also don’t understand/remember what the capabilities inst var is used for.  You could just take out the #ifTrue: line if it’s aesthetically displeasing. 

I mean if I had left the #ifTrue: line (& comment) out would we even be talking about this?  Bad 302 handling hasn’t been a problem for a while based on your analysis of the change history. 


I think you can configure zinc to give you a 302 for every request to a url right if you append something like a UUID as the last path element eg 

‘Http://localhost/always-redirect/‘ , UUID new asString

And that would prevent the browser caching the redirect permanently.  I’ll try to remember why the 302 was occurring but I think it was redirecting from http to https


But the headers that have the capabilities don’t come through in the 302 so either selenium needs to be compelled to resend those headers or I don’t know what

**Comment by Rinzwind** [comment]
The code for handling responses with status code 302 or 303 to the "POST /session" requests was originally added for compatibility with older versions of selenium server. That is, Parasol-Core-KrisGybels.24 adapted Parasol to work with v2.35.0, while this was modified in Parasol-Core-KrisGybels.25 to still support older versions as well. I'd like to better understand why a recent version of selenium server like v3.13.0 would still require this old compatibility code. Could you tell us how to reproduce such a response and/or give a dump of one?

As for the capabilities: if the response to the "POST /session" request does not include them, I'm not sure how to get them. Previously, the JSON wire protocol specified that the server should support GET requests on "/session/{sessionID}" with the response including the session's capabilities. But this was dropped from the newer W3C webdriver protocol (see [issue #12](https://github.com/SeasideSt/Parasol/issues/12#issuecomment-332816020)). I'm not sure the newer protocol specifies a way of getting the capabilities other than from the response to the "POST /session" request.

**Comment by pdebruic** [comment]
Here is a dump
```BPRemoteWebDriver(Object)>>error:
BPRemoteWebDriver>>sessionIdFromResponse:
BPRemoteWebDriver>>initWithCapabilities:
BPRemoteWebDriver class>>withCapabilities:
BPWebDriverManagerResource>>driverWithCapabilities:on:
StafferParasolCalendarMovementTests(BPWebDriverTestCase)>>setUp
StafferParasolCalendarMovementTests(StafferParasolTests)>>setUp
[ self setUp.
self performTest ] in StafferParasolCalendarMovementTests(TestCase)>>runCase in Block: [ self setUp....
BlockClosure>>ensure:
StafferParasolCalendarMovementTests(TestCase)>>runCase
StafferParasolCalendarMovementTests(BPWebDriverTestCase)>>runCase
[ aTestCase runCase ] in [ [ aTestCase runCase ]
	on: Halt
	do: [ :halt | 
		"if test was halted we should resume all background failures 
			to debug all of them together with test process"
		failedProcesses keysDo: #resume.
		halt pass ] ] in TestExecutionEnvironment>>runTestCaseSafelly: in Block: [ aTestCase runCase ]
BlockClosure>>on:do:
[ [ aTestCase runCase ]
	on: Halt
	do: [ :halt | 
		"if test was halted we should resume all background failures 
			to debug all of them together with test process"
		failedProcesses keysDo: #resume.
		halt pass ] ] in TestExecutionEnvironment>>runTestCaseSafelly: in Block: [ [ aTestCase runCase ]...
BlockClosure>>on:do:
TestExecutionEnvironment>>runTestCaseSafelly:
[ self runTestCaseSafelly: aTestCase ] in [ [ self runTestCaseSafelly: aTestCase ]
	ensure: [ testCompleted := true.
		watchDogSemaphore signal ].	"signal that test case completes"
self checkForkedProcesses ] in TestExecutionEnvironment>>runTestCase: in Block: [ self runTestCaseSafelly: aTestCase ]
BlockClosure>>ensure:
[ [ self runTestCaseSafelly: aTestCase ]
	ensure: [ testCompleted := true.
		watchDogSemaphore signal ].	"signal that test case completes"
self checkForkedProcesses ] in TestExecutionEnvironment>>runTestCase: in Block: [ [ self runTestCaseSafelly: aTestCase ]...
BlockClosure>>ifCurtailed:
TestExecutionEnvironment>>runTestCase:
[ testEnv runTestCase: aTestCase ] in DefaultExecutionEnvironment>>runTestCase: in Block: [ testEnv runTestCase: aTestCase ]
[ self value: anExecutionEnvironment.
anExecutionEnvironment activated.
aBlock value ] in CurrentExecutionEnvironment class>>activate:for: in Block: [ self value: anExecutionEnvironment....
BlockClosure>>ensure:
CurrentExecutionEnvironment class>>activate:for:
TestExecutionEnvironment(ExecutionEnvironment)>>beActiveDuring:
DefaultExecutionEnvironment>>runTestCase:
CurrentExecutionEnvironment class>>runTestCase:
StafferParasolCalendarMovementTests(TestCase)>>runCaseManaged
[ aTestCase announce: TestCaseStarted withResult: self.
aTestCase runCaseManaged.
aTestCase announce: TestCaseEnded withResult: self.
self addPass: aTestCase ] in TestResult>>runCaseForDebug: in Block: [ aTestCase announce: TestCaseStarted withResult: ...etc...
```

To get it I installed parasol in a pharo 6.1 image on mac, started the selenium jar file with 



I don't understand how to gain any of the knowledge you are asking about.  I'm not going to look into the internals of Selenium to see why its now throwing a 302 response when setting up a webdriver 


Why do the capabilities matter?

**Comment by Rinzwind** [comment]
For reference, the documentation about “POST /session” can be found at the following two pages, for the older JSON wire protocol and the newer W3C protocol respectively:

* https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol/226c14a5ba47adb880415790c9513235b7d01e64#session-1
* https://www.w3.org/TR/2018/REC-webdriver1-20180605/#new-session

I cannot tell how a response with status code 302 or 303 (and no body) would still be in accordance with these specifications (as I mentioned above, older versions of selenium/webdriver did respond using these status codes, but I'm not sure why newer versions would still exhibit that behavior).

**Comment by Rinzwind** [comment]
Closing this pull request, see: https://github.com/SeasideSt/Parasol/issues/14#issuecomment-506222317.

**Pull request closed without merging**
