### PR TITLE
separated parasol and seaside

### PR DESCRIPTION
**Pull request by noha**
Separated seaside and parasol as much as possible with introducing Parasol-Seaside package

### CODE REVIEW

**Comment by jbrichau** [comment]
Hi Norbert,

As the failing tests indicate, it seems `STONWriter` cannot be used to produce JSON from Smalltalk objects. From the comment of STONWriter: 'only STON listClass and STON mapClass instances are allowed as composite objects'.

**Comment by noha** [comment]
I'll take a look

**Comment by Rinzwind** [comment]
Hmm Travis Job #726.3 has [two tests failing on STONWriterError](https://travis-ci.org/SeasideSt/Parasol/jobs/417284226#L946-L966)?

**Comment by noha** [comment]
I try to work on that next week.

**Comment by Rinzwind** [comment]
The problem with `BPRemoteWebDriverTestCase>>testFindElementByXPath` in the [Pharo 5 job](https://travis-ci.org/SeasideSt/Parasol/jobs/428245448#L1133) seems to come down to the following:

```
d := Dictionary with: 'using'->'xpath' with: 'value'->'//div[@id=''testDiv1'']'.
{ d asJson. STONJSON toString: d }
```
↪︎ `#('{"using": "xpath", "value": "//div[@id=''testDiv1'']"}' '{"using":"xpath","value":"//div[@id=\''testDiv1\'']"}')`

The STON string escapes the single quotes around `testDiv1`, which is not correct JSON. The “escape” rule in the JSON grammar on [json.org](https://json.org) allows double quote, but not single quote:

```
string
    '"' characters '"'
characters
    ""
    character characters
character
    '0020' . '10ffff' - '"' - '\'
    '\' escape
escape
    '"'
    '\'
    '/'
    'b'
    'n'
    'r'
    't'
    'u' hex hex hex hex
```

**Comment by noha** [comment]
Ston baseline is now merged and the build should succeed. But there is a few travis problems not related to parasol. Could you trigger those builds again?

https://travis-ci.org/SeasideSt/Parasol/builds/428920120?utm_source=github_status&utm_medium=notification <https://travis-ci.org/SeasideSt/Parasol/builds/428920120?utm_source=github_status&utm_medium=notification>

**Comment by jbrichau** [comment]
I triggered them again. Since a couple of weeks, Squeak has an issue downloading the github zip file on 3 out 4 builds (or something like that). Gemstone builds are more annoying as they hit the github download rate limit.

**Comment by jbrichau** [comment]
@noha I think we can ignore it. Downloading Seaside in Squeak 5.1 is failing in all builds.

**Comment by noha** [comment]
Ok, good. So anyone of you is going to merge?

**Pull request merged**
